#pragma once

// Window
#define WINDOW_CLASS_NAME L"Castlevania"
#define MAIN_WINDOW_TITLE L"Castlevania"

#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 240

#define MAX_FRAME_RATE 120

#define BACKGROUND_WIDTH 1536

// Input

#define DIRECTINPUT_VERSION 0x0800
#define KEYBOARD_BUFFER_SIZE 1024

// Mario
#define MARIO_WALKING_SPEED	0.1f 
#define MARIO_JUMP_SPEED_Y 0.5f
#define MARIO_JUMP_DEFLECT_SPEED 0.2f
#define MARIO_GRAVITY 0.002f
#define MARIO_DIE_DEFLECT_SPEED 0.5f

#define MARIO_STATE_IDLE 0
#define MARIO_STATE_WALKING_RIGHT 100
#define MARIO_STATE_WALKING_LEFT 200
#define MARIO_STATE_JUMP 300
#define MARIO_STATE_DIE	400

#define	MARIO_LEVEL_SMALL 1
#define	MARIO_LEVEL_BIG 2

#define MARIO_BIG_BBOX_WIDTH 15
#define MARIO_BIG_BBOX_HEIGHT 27

#define MARIO_SMALL_BBOX_WIDTH 13
#define MARIO_SMALL_BBOX_HEIGHT 15

#define MARIO_UNTOUCHABLE_TIME 5000

#define MARIO_ANI_BIG_IDLE_RIGHT 0
#define MARIO_ANI_BIG_IDLE_LEFT	1
#define MARIO_ANI_SMALL_IDLE_RIGHT 2
#define MARIO_ANI_SMALL_IDLE_LEFT 3

#define MARIO_ANI_BIG_WALKING_RIGHT	4
#define MARIO_ANI_BIG_WALKING_LEFT 5
#define MARIO_ANI_SMALL_WALKING_RIGHT 6
#define MARIO_ANI_SMALL_WALKING_LEFT 7

#define MARIO_ANI_DIE 8

// Goomba
#define GOOMBA_WALKING_SPEED 0.05f;

#define GOOMBA_BBOX_WIDTH 16
#define GOOMBA_BBOX_HEIGHT 15
#define GOOMBA_BBOX_HEIGHT_DIE 9

#define GOOMBA_STATE_WALKING 100
#define GOOMBA_STATE_DIE 200

#define GOOMBA_ANI_WALKING 0
#define GOOMBA_ANI_DIE 1

// Brick
#define BRICK_BBOX_WIDTH 32
#define BRICK_BBOX_HEIGHT 32