#pragma once

// Window
#define WINDOW_CLASS_NAME L"Castlevania"
#define MAIN_WINDOW_TITLE L"Castlevania"

#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 240

#define MAX_FRAME_RATE 120

#define BACKGROUND_WIDTH 1536

// Input
#define DIRECTINPUT_VERSION 0x0800
#define KEYBOARD_BUFFER_SIZE 1024

// Simon
#define SIMON_WALKING_SPEED 0.1f 
#define SIMON_JUMP_SPEED 0.5f
#define SIMON_GRAVITY 0.002f

#define SIMON_STATE_IDLE 1
#define SIMON_STATE_WALKING_RIGHT 2
#define SIMON_STATE_WALKING_LEFT 3
#define SIMON_STATE_SITTING 4
#define SIMON_STATE_JUMPING 5
#define SIMON_STATE_SITTING_AND_ATTACKING 6
#define SIMON_STATE_STANDING_AND_ATTACKING 7

#define SIMON_BBOX_WIDTH 60
#define SIMON_BBOX_HEIGHT 62 // 66

#define SIMON_ANI_IDLE_LEFT	0
#define SIMON_ANI_WALKING_LEFT 1
#define SIMON_ANI_SITTING_LEFT 2
#define SIMON_ANI_JUMPING_LEFT 3
#define SIMON_ANI_SITTING_LEFT_AND_HITTING 4
#define SIMON_ANI_STANDING_LEFT_AND_HITTING 5

#define SIMON_ANI_IDLE_RIGHT 6
#define SIMON_ANI_WALKING_RIGHT	7
#define SIMON_ANI_SITTING_RIGHT 8
#define SIMON_ANI_JUMPING_RIGHT 9
#define SIMON_ANI_SITTING_RIGHT_AND_HITTING 10
#define SIMON_ANI_STANDING_RIGHT_AND_HITTING 11

// Brick
#define BRICK_BBOX_WIDTH 32
#define BRICK_BBOX_HEIGHT 32

// Big candles
#define BIG_CANDLE_BBOX_WIDTH 31
#define BIG_CANDLE_BBOX_HEIGHT 63